groups:
- name: backup-tools
  rules:
  # Application Health Alerts
  - alert: BackupToolsDown
    expr: up{job="backup-tools-satellite"} == 0
    for: 1m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Backup Tools application is down"
      description: "Backup Tools application has been down for more than 1 minute"
      runbook_url: "https://docs.example.com/runbooks/backup-tools-down"

  - alert: PushGatewayDown
    expr: up{job="pushgateway"} == 0
    for: 1m
    labels:
      severity: warning
      service: pushgateway
    annotations:
      summary: "Push Gateway is down"
      description: "Prometheus Push Gateway has been down for more than 1 minute"
      runbook_url: "https://docs.example.com/runbooks/pushgateway-down"

  # HTTP Request Alerts
  - alert: HighErrorRate
    expr: |
      (
        rate(promhttp_metric_handler_requests_total{job="backup-tools-satellite",code!="200"}[5m]) /
        rate(promhttp_metric_handler_requests_total{job="backup-tools-satellite"}[5m])
      ) * 100 > 5
    for: 2m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High HTTP error rate detected"
      description: "HTTP error rate is {{ $value }}% for the last 5 minutes"
      runbook_url: "https://docs.example.com/runbooks/high-error-rate"

  - alert: VeryHighErrorRate
    expr: |
      (
        rate(promhttp_metric_handler_requests_total{job="backup-tools-satellite",code!="200"}[5m]) /
        rate(promhttp_metric_handler_requests_total{job="backup-tools-satellite"}[5m])
      ) * 100 > 10
    for: 1m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Very high HTTP error rate detected"
      description: "HTTP error rate is {{ $value }}% for the last 5 minutes"
      runbook_url: "https://docs.example.com/runbooks/very-high-error-rate"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(promhttp_metric_handler_request_duration_seconds_bucket{job="backup-tools-satellite"}[5m])) > 1
    for: 2m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High HTTP response time detected"
      description: "95th percentile response time is {{ $value }}s"
      runbook_url: "https://docs.example.com/runbooks/high-response-time"

  - alert: VeryHighResponseTime
    expr: histogram_quantile(0.95, rate(promhttp_metric_handler_request_duration_seconds_bucket{job="backup-tools-satellite"}[5m])) > 5
    for: 1m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Very high HTTP response time detected"
      description: "95th percentile response time is {{ $value }}s"
      runbook_url: "https://docs.example.com/runbooks/very-high-response-time"

  # System Resource Alerts
  - alert: HighMemoryUsage
    expr: go_memstats_heap_alloc_bytes{job="backup-tools-satellite"} > 100 * 1024 * 1024 * 1024  # 100MB
    for: 5m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is {{ $value | humanize1024 }}B"
      runbook_url: "https://docs.example.com/runbooks/high-memory-usage"

  - alert: VeryHighMemoryUsage
    expr: go_memstats_heap_alloc_bytes{job="backup-tools-satellite"} > 500 * 1024 * 1024 * 1024  # 500MB
    for: 2m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Very high memory usage detected"
      description: "Memory usage is {{ $value | humanize1024 }}B"
      runbook_url: "https://docs.example.com/runbooks/very-high-memory-usage"

  - alert: HighGoroutineCount
    expr: go_goroutines{job="backup-tools-satellite"} > 1000
    for: 5m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High goroutine count detected"
      description: "Goroutine count is {{ $value }}"
      runbook_url: "https://docs.example.com/runbooks/high-goroutine-count"

  - alert: VeryHighGoroutineCount
    expr: go_goroutines{job="backup-tools-satellite"} > 5000
    for: 2m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Very high goroutine count detected"
      description: "Goroutine count is {{ $value }}"
      runbook_url: "https://docs.example.com/runbooks/very-high-goroutine-count"

  # Garbage Collection Alerts
  - alert: HighGarbageCollectionTime
    expr: rate(go_gc_duration_seconds_sum{job="backup-tools-satellite"}[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High garbage collection time detected"
      description: "GC time is {{ $value }}s per second"
      runbook_url: "https://docs.example.com/runbooks/high-gc-time"

  - alert: VeryHighGarbageCollectionTime
    expr: rate(go_gc_duration_seconds_sum{job="backup-tools-satellite"}[5m]) > 0.5
    for: 2m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Very high garbage collection time detected"
      description: "GC time is {{ $value }}s per second"
      runbook_url: "https://docs.example.com/runbooks/very-high-gc-time"

  # Satellite Operation Alerts
  - alert: HighSatelliteUploadErrors
    expr: rate(satellite_upload_errors_total{job="backup-tools-satellite"}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High satellite upload error rate detected"
      description: "Upload error rate is {{ $value }} errors per second for bucket {{ $labels.bucket }}"
      runbook_url: "https://docs.example.com/runbooks/high-upload-errors"

  - alert: HighSatelliteDownloadErrors
    expr: rate(satellite_download_errors_total{job="backup-tools-satellite"}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High satellite download error rate detected"
      description: "Download error rate is {{ $value }} errors per second for bucket {{ $labels.bucket }}"
      runbook_url: "https://docs.example.com/runbooks/high-download-errors"

  - alert: HighSatelliteRequestErrors
    expr: rate(satellite_request_errors_total{job="backup-tools-satellite"}[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High satellite request error rate detected"
      description: "Request error rate is {{ $value }} errors per second for {{ $labels.error_type }}"
      runbook_url: "https://docs.example.com/runbooks/high-request-errors"

  - alert: HighSatelliteOperationDuration
    expr: histogram_quantile(0.95, rate(satellite_upload_duration_seconds_bucket{job="backup-tools-satellite"}[5m])) > 30
    for: 5m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "High satellite operation duration detected"
      description: "95th percentile upload duration is {{ $value }}s for bucket {{ $labels.bucket }}"
      runbook_url: "https://docs.example.com/runbooks/high-operation-duration"

  - alert: VeryHighSatelliteOperationDuration
    expr: histogram_quantile(0.95, rate(satellite_upload_duration_seconds_bucket{job="backup-tools-satellite"}[5m])) > 60
    for: 2m
    labels:
      severity: critical
      service: backup-tools
    annotations:
      summary: "Very high satellite operation duration detected"
      description: "95th percentile upload duration is {{ $value }}s for bucket {{ $labels.bucket }}"
      runbook_url: "https://docs.example.com/runbooks/very-high-operation-duration"

  # Service Discovery Alerts
  - alert: ServiceDiscoveryFailure
    expr: up{job="backup-tools-satellite"} == 0 and up{job="pushgateway"} == 0
    for: 1m
    labels:
      severity: critical
      service: monitoring
    annotations:
      summary: "Service discovery failure"
      description: "Both backup-tools-satellite and pushgateway services are down"
      runbook_url: "https://docs.example.com/runbooks/service-discovery-failure"

  # Data Loss Prevention Alerts
  - alert: NoRecentUploads
    expr: rate(satellite_upload_duration_seconds_count{job="backup-tools-satellite"}[1h]) == 0
    for: 30m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "No recent uploads detected"
      description: "No uploads have been detected in the last hour"
      runbook_url: "https://docs.example.com/runbooks/no-recent-uploads"

  - alert: NoRecentDownloads
    expr: rate(satellite_download_duration_seconds_count{job="backup-tools-satellite"}[1h]) == 0
    for: 30m
    labels:
      severity: warning
      service: backup-tools
    annotations:
      summary: "No recent downloads detected"
      description: "No downloads have been detected in the last hour"
      runbook_url: "https://docs.example.com/runbooks/no-recent-downloads"
